name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Add safe directory
        run: git config --global --add safe.directory /home/nihcas/server/portfolio

      - name: Update code on server
        run: |
          cd /home/nihcas/server/portfolio
          git fetch origin main
          git reset --hard origin/main
          git clean -fd

      - name: Install dependencies
        run: |
          cd /home/nihcas/server/portfolio
          pnpm install

      - name: Build
        run: |
          cd /home/nihcas/server/portfolio
          pnpm run build

      - name: Restart PM2
        run: |
          cd /home/nihcas/server
          pm2 stop portfolio || true
          pm2 delete portfolio || true
          pm2 start ecosystem.config.js --only portfolio
          pm2 save

      # SLACK NOTIFICATION
      - name: notify Slack on Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": "✅ *Deployment Successful!*\n• Repository: ${{ github.repository }}\n• Branch: ${{ github.ref_name }}\n• Commit: ${{ github.sha }}\n• Author: ${{ github.actor }}\n• Message: ${{ github.event.head_commit.message }}\n• Action: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

      # SLACK NOTIFICATION ON FAILURE
      - name: notify Slack on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": "❌ *Deployment Failed!* \n• Repository: ${{ github.repository }}"
            • Branch: ${{ github.ref_name }}
            • Commit: ${{ github.sha }}
            • Author: ${{ github.actor }}
            • Action: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            }' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
